name = "Simrel"
uuid = "fc0daaf5-2141-43a3-8ee3-e4cc39e6b89e"
authors = ["Raju Rimal"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
